# An example, Create user 'max':
# Template creates a new user "max", adds public ssh key, and grants root-level privileges to "max" in the sudo group.
---
- hosts: local
  become: yes
  become_user: root
  tasks:
  - name: Create user 'max'
    user:
      name: max
      state: present
      groups: sudo
      append: yes
  - name: Add SSH key to 'max'
    authorized_key:
      user: max
      key: "{{ lookup('file', '~/.ssh/clave_aws.pub') }}"
      state: present
  - name: Give root permissions to 'max'
    lineinfile:
      dest: /etc/sudoers
      regexp: '^%sudo'
      line: '%max ALL=(ALL) NOPASSWD: ALL'
